version: '3'
services:
  api:
    container_name: mf-api--symfony
    build:
      context: ./
    ports:
      - "${WEB_PORT:-8555}:8080"
    image: mafio69/mf-symfony
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVERNAME=api.mf-symfony.test
      - SERVERALIAS=www.mf-symfony.test
      - DRUSH_VERSION=8/9
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2048M}
      - WEB_PORT=${WEB_PORT:-8888}
      - APP_NAME=${APP_NAME:-mf-db}
      - DATABASE_HOST=${DATABASE_HOST:-database}
      - PHP_SENDMAIL_DOMAIN=localhost
      - APP_ENV=${APP_ENV:-local}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PORT_LOCAL=${DATABASE_PORT_LOCAL}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - SOCKET=${SOCKET:-~}
      - APP_DEBUG=${APP_DEBUG:-1}
      - EMAIL_USER=${EMAIL_USER:-user}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-password}
      - EMAIL_HOST=${EMAIL_HOST:-mailtrap}
      - XDEBUG_MODE=${XDEBUG_MODE}
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
      - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT:-9003}
      - DISPLAY_ERROR=${DISPLAY_ERROR}
    volumes:
      - ./main:/main
      - ./logs/symfony-logs:/main/var/log
    links:
      - database:mysql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${WEB_PORT}" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

  database:
    container_name: mf-api--mysql
    ports:
      - "${DATABASE_PORT_LOCAL:-3310}:3306"
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  mailtrap:
    container_name: mf-api--mailtrap
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1033:1025" # smtp server
      - "8033:8025" # web ui

networks:
  default:
    external:
      name: mf-net-test
volumes:
  mysql-data-proxy:
